---
title: "explanation"
author: "csaybar&taenja"
date: "1/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
```

## 1. Prepare data

```{r}
x <- st_read("data/sen_slope.json")
weight <- "sen_slope"
value <- x[[weight]]
plot(x[weight])
```

## 2. sum up total value

```{r}
print(value)
valueTotal <- sum(value, na.rm = TRUE)
print(valueTotal)
meanSizeError <- 100
x.iter <- x
```

## 3. iterate until itermax is reached

```{r}
z <- 1
x.iter_geom <- sf::st_geometry(x.iter)
centroids_sf <- sf::st_centroid(x.iter_geom)
st_crs(centroids_sf) <- sf::st_crs(NULL)
centroids <- do.call(rbind, centroids_sf)
plot(centroids_sf)
```


### 3.1 area for polygons and total area

```{r}
area <- as.numeric(sf::st_area(x.iter))
areaTotal <- as.numeric(sum(area))
area[area < 0] <- 0
print(areaTotal)
```

### 3.2 prepare force field calculations

```{r}
desired <- areaTotal * value / valueTotal
desired[desired == 0] <- 0.01 # set minimum size to prevent inf values size Error
radius <- sqrt(area / pi)
mass <- sqrt(desired / pi) - sqrt(area / pi)
```

### 3.3 Estimate the error

```{r}
sizeError <- apply(cbind(area, desired), 1, max) / apply(cbind(area, desired), 1, min)
meanSizeError <- mean(sizeError, na.rm = TRUE)
forceReductionFactor <- 1 / (1 + meanSizeError)
message(paste0("Mean size error for iteration ", z , ": ", meanSizeError))
```


### 3.5 Estimate distance

```{r}
pts <- sf::st_coordinates(x.iter_geom[[1]])
plot(x.iter_geom[1])
idx <- unique(pts[, colnames(pts) %in% c("L1", "L2", "L3")])
newpts <- pts[pts[, "L1"] == idx[1, "L1"] & pts[, "L2"] == idx[1, "L2"], c("X", "Y")]
distances <- apply(centroids, 1, function(pt) {
  ptm <- matrix(pt, nrow=nrow(newpts), ncol=2, byrow=T)
  sqrt(rowSums((newpts - ptm)^2))
})
print(dim(distances))
```

### 3.6 Estimate deformation

```{r}
for (j in  seq_len(nrow(centroids))) {
  distance <- distances[, j]
      
  # calculate force vector
  Fij <- mass[j] * radius[j] / distance
  Fbij <- mass[j] * (distance / radius[j]) ^ 2 * (4 - 3 * (distance / radius[j]))
  Fij[distance <= radius[j]] <- Fbij[distance <= radius[j]]
  Fij <- Fij * forceReductionFactor*100 / distance
      
  # calculate new border coordinates
  newpts_01 <- newpts + cbind(X1 = Fij, X2 = Fij) * (newpts - centroids[rep(j, nrow(newpts)), ])
}
plot(newpts)
points(newpts_01, col = "red")
```

